# Generated by Django 2.1 on 2018-08-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180821_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/$D/'),
        ),
    ]
