# Generated by Django 2.1 on 2018-08-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermembership',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='location',
        ),
    ]
