# Generated by Django 2.1 on 2018-08-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='media_root'),
        ),
    ]
